### ISSUE TITLE
typos?

### ISSUE THREAD

**Issue by cx20** [SaschaWillems/webgl#1]
I think that it is a typo.

https://github.com/SaschaWillems/webgl/blob/master/utils/webglutils.js

```
gl = canvas.getContext("experiemental-" + target, { antialias: antialiasing });
```

"experiemental-" 
-> "experimental-"

**Comment by SaschaWillems** [comment]
Yes, that's a typo. Thanks for spotting this!

**Comment by cx20** [comment]
Thanks!
